### ISSUE TITLE
Decision of database to be used

### ISSUE THREAD

**Issue by bhautikbharadava** [Grommerce/grommerce-backend#8]
Which database to use from MySQL, PostgresDB, MongoDB?

**Comment by reeversedev** [comment]
My suggestion is to use PostgresDB because apparently we'll be able to use SQL databases with JSON support.

**Comment by meetzaveri** [comment]
Mainly suggestion is that people are suggesting NoSQL database. SQL database performance degrades as no. of items grow i.e. scalability cannot be acheived through SQL database.

Sources suggest Cassandra would be better choice as NoSQL.

https://www.ebayinc.com/stories/blogs/tech/cassandra-data-modeling-best-practices-part-1/

https://www.youtube.com/watch?v=2sRoLMmwEiQ

**Comment by meetzaveri** [comment]
A good answer on quora. 

https://www.quora.com/What-technologies-are-needed-to-build-an-e-commerce-website/answer/Jake-Cook-8?ch=10&share=8a18f8ac&srid=huYHe
